# Generated by Django 2.0 on 2017-12-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.CharField(max_length=500)),
                ('data', models.DateField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('vinculo', models.CharField(choices=[('', 'Selecione'), ('A', 'Aluno'), ('S', 'Servidor')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=250)),
                ('logradouro', models.CharField(max_length=250)),
                ('numEndereco', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=14)),
                ('dataCadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatario', to='caronas.Usuario'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remetente', to='caronas.Usuario'),
        ),
    ]
